services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-default_secret_key_for_development}
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - sqlite_data:/app/db
      - ./log:/app/log
    restart: unless-stopped
    command: sh -c "mkdir -p tmp/pids && RAILS_ENV=development bundle exec puma -C config/puma.rb"

volumes:
  sqlite_data:
    driver: local